### ISSUE TITLE
[Todo] Style adjustment for daily-overview page

### ISSUE THREAD

**Issue by shc261392** [MyDataTaiwan/mylog14#100]
# Issue description

1. Center the Main Header title

2. Fix that the lower part of the countdown animation overlap with the dividing line

**Comment by bafu** [comment]
Use this issue to track the 1st problem, and create issue #139 for the 2nd problem.

The 1st problem has been fixed in PR #111.

**Comment by tammyyang** [comment]
Mid-sprint 會再討論一下確實的修改項目

**Comment by wcchung** [comment]
verified in ios 0.8.2 & android 0.8.1
