### ISSUE TITLE
[Todo] Add a hint text for body temperature picker

### ISSUE THREAD

**Issue by shc261392** [MyDataTaiwan/mylog14#102]
# Issue description

1. On add-record page, show a 體溫 text to tell the user they are asked to pick the body temperature

**Comment by CS6** [comment]
note 無預設標題欄位，只好以按鈕充當文本
![image](https://user-images.githubusercontent.com/16307922/81560839-c703a780-93c4-11ea-895a-2435cdd5e881.png)

**Comment by CS6** [comment]
fixed
