### ISSUE TITLE
[Todo] ios  switching languages from  Japanese display bug

### ISSUE THREAD

**Issue by CS6** [MyDataTaiwan/mylog14#115]
![image](https://user-images.githubusercontent.com/16307922/81212362-61e83480-9007-11ea-8c3a-0d786d9942d5.png)

`感謝 Dixon 發現問題`

**Comment by tammyyang** [comment]
According to the feedback from Dayuan, this has been fixed

**Comment by tammyyang** [comment]
@wcchung please help verify

**Comment by wcchung** [comment]
fixed verified on ios 0.8.2
