### ISSUE TITLE
No way to cancel "Add entry" action

### ISSUE THREAD

**Issue by dixonsiu** [MyDataTaiwan/mylog14#118]
No way to cancel "Add entry" action without shutting down the app.

Suggestion: Add a "Back" arrow or "X" button to allow the user to close the screen.

![Image from iOS (1)](https://user-images.githubusercontent.com/29846750/81277409-58a2aa80-908f-11ea-89f3-8f5e159890e0.png)

**Comment by CS6** [comment]
hi @dixonsiu the feature is the version already fixed 🙀
Are you telling me version & convenient device you are using 🧐

**Comment by dixonsiu** [comment]
Updated to the latest 0.6.2 version and confirmed this issue is fixed.
