### ISSUE TITLE
[Bug report] Vertical scrollbar is not displayed when an item is expanded

### ISSUE THREAD

**Issue by dixonsiu** [MyDataTaiwan/mylog14#124]
# No scrollbar even though item is expanded  
![Image from iOS (11)](https://user-images.githubusercontent.com/29846750/81283673-f9956380-9097-11ea-8a82-922c4722a6ec.png)

# Scroll down to see the symptoms  
![Image from iOS (10)](https://user-images.githubusercontent.com/29846750/81283693-02863500-9098-11ea-8130-311617d820fc.png)

**Comment by wcchung** [comment]
issue fixed in 0.8.4 release
