### ISSUE TITLE
[Bug report] Detail screen only display one location despite of multi-entries

### ISSUE THREAD

**Issue by dixonsiu** [MyDataTaiwan/mylog14#126]
I went to the supermarket and came back but the detail screen shows only the last location in the map.

**Comment by tammyyang** [comment]
@dixonsiu did you record symptom in the suprtmarket?

**Comment by dixonsiu** [comment]
I think I just record the temerature.

**Comment by wcchung** [comment]
Issue fixed in beta7 release
