### ISSUE TITLE
[Todo]  Remove deleted photos from dataStore.dailyRecords$.photos

### ISSUE THREAD

**Issue by CS6** [MyDataTaiwan/mylog14#130]
Click on the "Delete" button on the top right corner to delete the photo
Can delete photos

but, the photos in the ` dataStore.dailyRecords$.photos` list in this object have not been removed

**Comment by dixonsiu** [comment]
I think it display the following list and detail screesn with white squares afeter deleting all photos.  
![Image from iOS (16)](https://user-images.githubusercontent.com/29846750/81404441-71cf5800-9170-11ea-882b-6a5733420857.png)
![Image from iOS (17)](https://user-images.githubusercontent.com/29846750/81404448-73991b80-9170-11ea-8771-9d3c494cf4c5.png)

**Comment by dixonsiu** [comment]
Related issues #135 & #136
