### ISSUE TITLE
[Bug report] Chinese labels are displayed even when theniOS language is set to English

### ISSUE THREAD

**Issue by dixonsiu** [MyDataTaiwan/mylog14#132]
# List screen  
![Image from iOS (12)](https://user-images.githubusercontent.com/29846750/81401188-c3c0af80-9169-11ea-89ca-bd983c79a2fc.png)

# Add record screen  
![Image from iOS (13)](https://user-images.githubusercontent.com/29846750/81401195-c6230980-9169-11ea-8020-3010c1ef940e.png)

**Comment by CS6** [comment]
fixed
