### ISSUE TITLE
[FR] Button label does not clearly inform the user the action

### ISSUE THREAD

**Issue by dixonsiu** [MyDataTaiwan/mylog14#134]
# First dialog  
Asking whether data should be uploded  
1. Cancel - do not create link (meaning no sharing of data)  
1. Confirm - upload data and create link  
![Image from iOS (14)](https://user-images.githubusercontent.com/29846750/81402462-68dc8780-916c-11ea-857a-358dc86a039e.png)

# Second dialog (current)  
The data is already uploaed. Therefore, both buttons just close the dialog without extra operations.  
1. Cancel - close the dialog  
1. Confirm - close the dialog  
![Image from iOS (15)](https://user-images.githubusercontent.com/29846750/81402532-91648180-916c-11ea-81ae-22fe4dcea9ea.png)

# Second dialog (suggestion)  
1. Close - close the dialog

**Comment by wcchung** [comment]
UX/UI change, the issue is not exist now.
