### ISSUE TITLE
[Bug Report] Cannot install the new version when you have an old version

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#147]
**Description**
when your Android  device had the old version ( mylog14 v 0.6.2 ) , can't install the new version (V0.6.4_beta3)

**Steps to Reproduce**

1. Download the "MyLog14_0.6.4_beta3.apk"
2. put it into device 
3. press the " MyLog14_0.6.4_beta3.apk " to install 
4. it will show " 未安裝應用程式 "

**Expected behavior**

* Expected: press the " MyLog14_0.6.4_beta3.apk " to install . it will normal coverage the old version
                   and can see the before record data still in the app 
* Actual: can't install the new version. you have to be remove the old version . instill the new one.

**Logs**
![Screenshot_20200514-094459](https://user-images.githubusercontent.com/62582260/81798474-abbea680-9542-11ea-9478-3c8c7c82f2de.png)

**Environment**

* MyLog:  v0.6.4_beta
* OS: HTC EXODUS 1s ,Android 8.1.0

**Comment by scott-dt** [comment]
james 說明因為舊版跟新版要是同一個 signature 才能安裝，理論上我們現在（及往後 release）都要固定用我現在更新的這個 signature ，但舊版 signature 沒辦法回頭改，所以最多就是現在這個版本 signature + enforce 以後 release 都要用現在這個版本 signature

**Comment by tammyyang** [comment]
based on @scott-dt 's comment, close the issue
