### ISSUE TITLE
[Bug Report] Record page no back button

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#150]
**Description**
Record page no back button

**Logs**
![IMG_0636](https://user-images.githubusercontent.com/62582260/81801741-7bc5d200-9547-11ea-997a-ead2354d4cbe.PNG)

**Environment**

* MyLog: V0.6.2
* OS:iphone 7 plus, ios 13.3.1

**Comment by CS6** [comment]
v0.6.4 fixed
