### ISSUE TITLE
[Bug Report] daily card the day cut into two lines

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#151]
**Description**
daily card the day cut into two lines

**Logs**
![IMG_0637](https://user-images.githubusercontent.com/62582260/81802050-f5f65680-9547-11ea-8201-d957306f44cf.PNG)

**Environment**

* MyLog: v0.6.2
* OS: iphone 7 plus, ios 13.3.1

**Comment by dixonsiu** [comment]
Good testing. My phone is iPhone 8 plus so cannot see this problem.

**Comment by CS6** [comment]
Maybe I can change text to rem in the next version
