### ISSUE TITLE
[FR] Show only simple symptoms and allow users to update to the full list later

### ISSUE THREAD

**Issue by tammyyang** [MyDataTaiwan/mylog14#158]
**Concept**
If we show only simple symptoms and allow users to update to the full list later

**Reason/Hypothesis**

We can help users to start with basic symptoms so that it is easier to start with because we know the full list is too much for new users and they don't need the full list most of the time.

**More Description (if any)**

This may also help us speed up App launching in the iOS platform.

**Suggested Implementation (if any)**

Not yet

**Comment by tammyyang** [comment]
大元送了一個 App 做喜怒哀樂的紀錄，測試中

**Comment by tammyyang** [comment]
需等待上架的實驗結果

**Comment by CS6** [comment]
已通過，目前正進行第二階段的測試

**Comment by tammyyang** [comment]
postpone to beta6 due to resource shortage

**Comment by tammyyang** [comment]
![UI proposal](https://user-images.githubusercontent.com/5687908/83558470-ae129000-a545-11ea-93a2-6012f10b9f4b.jpg)

**Comment by CS6** [comment]
![image](https://user-images.githubusercontent.com/16307922/83708751-98898d00-a64f-11ea-970e-093cbd0e4996.png)

**Comment by tammyyang** [comment]
1. 從 API 下載 or 本地?
  * 有 i18n 的問題，所以根據語系下載比較好
  * concern: 需要網路 => `預載 2 種，其他網路載` (至少也要預載一個組合，否則上架不會過)
  * 可以先做本地兩種，但擴充的時候還是要 API 
2. User 是否可以自在切換
  * 建議不行，不然在 data visualization 會太複雜 => `切換的時候會清除之前的資料，提供 alert`
  * 擴充? toggle 切換?
  * 建議不要在一開始的時候就詢問使用者是否要更換 (會影響上架, 推更新也會重審)

後續討論: i18n 架構
