### ISSUE TITLE
[Bug Report] Add record sceen - text is hidden when another symptom button is activated

### ISSUE THREAD

**Issue by dixonsiu** [MyDataTaiwan/mylog14#160]
**Description**
When you are adding a record, if you activate and add text to more than one symptom, he previous textarea becomes hidden and no way to display it again unless you deactivate adn activate the corresponding symptom again.

**Steps to Reproduce**

1. Click on '+' to add a record
2. Activate one symptom and type something
3. Activate the next symptom
4. Previous textarea is hidden

**Expected behavior**

* Expected: textarea should be displayed as long as it is not empty.
* Actual: textarea is hidden

**screenshots**
![Image from iOS (19)](https://user-images.githubusercontent.com/29846750/82314025-259fd580-9a04-11ea-8621-7404b4ef3eaa.png)

**Environment**

* MyLog: [v0.6.4 beta3]
* OS: [iOS 13]

**Comment by tammyyang** [comment]
改為 FR => 只輸入一個 note

**Comment by tammyyang** [comment]
Close this issue as multiple node field will be replaced by https://github.com/MyDataTaiwan/mylog14/issues/175
