### ISSUE TITLE
[UI Update] 首頁紀錄天數動畫

### ISSUE THREAD

**Issue by tammyyang** [MyDataTaiwan/mylog14#161]
**Update Purpose**
圓框倒數狀態深淡顏色不符合使用者期待，應互換

**UI Suggestion**

Page 10 of https://docs.google.com/presentation/d/1tGQ_2rPN_VCFr9LzV1O-gQF-zIV5Q59ANiljWAVQhCo/edit#slide=id.g842fae12e3_0_72

**More Description (if any)**

圓框倒數狀態深淡顏色應互換
淡色（灰色）表示已過時間
深色表示未過時間 ( 由內凹 => 改為外凸 )

**Comment by bafu** [comment]
目標是

* 深色代表經過的天數，形狀為外凸
* 淺色代表總共的天數，形狀為內凹

**Comment by tammyyang** [comment]
其他問題:

* 十四天後動畫要如何處理? (current proposal: 留在虛擬珍奶)

**Comment by wcchung** [comment]
Not fix in beta5

**Comment by CS6** [comment]
![image](https://user-images.githubusercontent.com/16307922/83708865-d8e90b00-a64f-11ea-8670-be19dff8414f.png)
