### ISSUE TITLE
[UI Update] 加入功能引導動畫

### ISSUE THREAD

**Issue by tammyyang** [MyDataTaiwan/mylog14#162]
**Update Purpose**
資訊設計不適當 → 功能缺乏引導

**UI Suggestion**

Page 12 of https://docs.google.com/presentation/d/1tGQ_2rPN_VCFr9LzV1O-gQF-zIV5Q59ANiljWAVQhCo/edit#slide=id.g842fae12e3_0_64

**More Description (if any)**

加入第一次使用引導操作動畫

**Comment by scott-dt** [comment]
beta 4 release fix
