### ISSUE TITLE
[UI Update] Change MyLog14 to MyLog

### ISSUE THREAD

**Issue by tammyyang** [MyDataTaiwan/mylog14#164]
**Update Purpose**
Marketing has decided to use MyLog instead of MyLog14

**UI Suggestion**

Update all icons from MyLog14 to MyLog and update text

**More Description (if any)**

Put more description here to help developers understand

**Comment by scott-dt** [comment]
first into app the logo still show MyLog14
![Screenshot_20200527-120837](https://user-images.githubusercontent.com/62582260/82977180-a9b11900-a013-11ea-863a-c15e44439109.png)

**Comment by wcchung** [comment]
The logo when I first launch the APP didn't change to new version
![IMAG4227](https://user-images.githubusercontent.com/12252921/83514637-97991400-a506-11ea-8515-25efb989a769.jpg)
