### ISSUE TITLE
[Bug Report] Application user acceptance text empty

### ISSUE THREAD

**Issue by paulcwang** [MyDataTaiwan/mylog14#167]
**Description**

Application user acceptance text empty

**Steps to Reproduce**

1. First time after logging in into MyLog14 application, it displays the Acceptance screen as follows [in French]

**Expected behavior**

* Expected: Before clicking the Accept button (Accord), the user should be given a text I believe that informs him how the data is managed, saved etc.
* Actual: Such text is still missing as shown in the snapshot above. 

**Logs**
See snapshot:
![image](https://user-images.githubusercontent.com/62894055/82656108-7a6d6700-9c23-11ea-8e74-67da94dd3ae0.png)

**Environment**

* MyLog: v0.6.1 
* OS: Android 10

**Comment by wcchung** [comment]
@paulcwang Due to the lacking of Terms & Conditions in French version. We put English version instead.
