### ISSUE TITLE
[Bug Report] The history blue icon folder does not allow result in any action

### ISSUE THREAD

**Issue by paulcwang** [MyDataTaiwan/mylog14#168]
**Description**

The history folder does not allow edit

**Steps to Reproduce**

The folder icon in blue at the bottom of the App page does not edit. [in French]

**Expected behavior**

Expected: When clicking on the blue folder icon, the user should be given to see files or history. 
Actual: No action when clicking on the blue icon. 

**Logs**
See snapshot:
image
![image](https://user-images.githubusercontent.com/62894055/82656917-cff64380-9c24-11ea-93c0-da47a7cc3069.png)

**Environment**

MyLog: v0.6.1
OS: Android 10

**Comment by wcchung** [comment]
This is as expected in current version
