### ISSUE TITLE
[FR] Only one note field in the symptom report

### ISSUE THREAD

**Issue by tammyyang** [MyDataTaiwan/mylog14#175]
**Concept**
If we provide only one note field in the buttom in the symptom report

**Reason/Hypothesis**

We can help user to simplify the process because we know users are now a little bit confusing about the multiple note fields.

**More Description (if any)**
https://github.com/MyDataTaiwan/mylog14/issues/160

**Suggested Implementation (if any)**

**Comment by tammyyang** [comment]
考慮跟之前資料的相容性，先移到下個 milestone

**Comment by wcchung** [comment]
Fixed in beta7  release
