### ISSUE TITLE
[FR] Can set font size in Settings

### ISSUE THREAD

**Issue by tammyyang** [MyDataTaiwan/mylog14#178]
**Concept**
If we provide options in the Settings to switch font size between small, and big

**Reason/Hypothesis**

We can help elder people to better read the words in the App because we know they may have difficulty seeing small words. 

**More Description (if any)**

Reference: https://github.com/MyDataTaiwan/mylog14/issues/209

**Suggested Implementation (if any)**

Settings => Font Size => choose from [Small, Large]

**Comment by scott-dt** [comment]
0.13.2 no this function (200901)

**Comment by wcchung** [comment]
Copy Information from #g0v Slack channel

---------

Sucre  1 day ago
https://www.figma.com/file/8N647WTrETwC8mG0eHmkLm/Component?node-id=6%3A0

字型選用 @youz 推薦的 Noto Sans
(可提供多國語系)

然後
我根據Ionic 提供的H1-H6以及P整理出 Normal 的尺寸
但 Ionic 的文字尺寸都偏小
有微調幾個地方
H1的尺寸
P的尺寸
增加新的 font-style 「註解」
Letter Spacing
Line High

三個不同的尺寸，我是設定倍數進行設計
前端不一定要設定倍數(e.g. 115%, 130%)，可以直接參考我在畫面中整理出來的 Font-style
打上倍數，是方便設計這裡記錄，字型尺寸選定的邏輯

上述的內容，都有標示在文字下方
要麻煩前端特別留意

Figma 可以直接查看 Code
也可以看到我的設定，CSS的地方可以下拉
查看IOS 以及 Android 的Code

目前我已經做到一個階段
如果要更好的話
重新繪製Mylog一兩個畫面，然後模擬套用三個尺寸的樣子
標示Mylog 每個頁面，應該套用H1,H2...等

這個部分麻煩 @Sherry Chung 幫我確認一下是否需要製作，還是先由前端修改後，我再進行微調

尊重你們的工作流程

**Comment by wcchung** [comment]
Copy information from Slack 

----------------

James  18:50
@sherry mylog 可以準備 release 了，但字體大小的法文跟日文要怎麼處理比較好
1. 我先用 Google 翻譯然後出一版，之後如果要更新翻譯再出一版
2. 請社群的人幫忙翻，等翻完再 release

sherry:joy:  18:57
@James 欠很多翻譯嗎?

James  18:58
Font Size Small Medium Large Very Large 這幾個

sherry:joy:  19:00
@James 我們現在不是只有 2 種字體大小嗎? XD
我可以請社群幫忙翻，不過這樣要等到明天才能 release，明天有人可以處理 release 嗎?

James  19:02
@sherry FR 上寫小中大三種，comment 裡面有提供 very large
如果不需要，也可以改成只要 Medium Large 就好

DaYuan:house_with_garden:  19:02
網路上找一下先頂著用（？

James  19:03
（拿掉選項只要一秒，不然先拿掉好了，因為我看特大好像會跑版滿嚴重的）

James  19:04
Font Size Medium Large 這樣

James  19:10
目前 release 可能還是需要大元協助，因為我 Android 卡 key sign 不過的問題，雖然我晚點可以全部砍掉重裝看看有沒有解，但不確定能 work

sherry:joy:  19:11
@James 我記得 #178 裡面好像只有寫兩種 font size 而已。我們先保留 layout 確認沒問題的兩種 (原本的大小 & 大字) 就好了。
翻譯的話應該可以先用 google 翻譯，我待會也用我的 iphone 切語系確認一下文字。
^^ @Tammy 有沒有其他建議呢?

James  19:11
我是看到 #209 的
Can change small, medium, large font size in Settings.
但 #178 的確只有寫 small & large

sherry:joy:  19:12
@James follow #178 即可，這次只要做最簡單的兩種字體切換就好。

James  19:12
總之目前是留兩種，那要寫 Medium Large 還是 Small Large
19:13
喔我看到 #178 是 Small Large
19:13
@sherry 那我想再確認一下，初次使用預設是 Small 還是 Large

tammy  19:14
@James Small
19:14
比較符合一般 app 的設定

James  19:15
ok

**Comment by wcchung** [comment]
sherry  19:30
@James 法文來了
Font Size: Taille
Small: Petit
Large: Grande

James  19:31
好快 跟 google 翻譯不一樣

sherry:joy:  19:33
replied to a thread:
好快 跟 google 翻譯不一樣
From Tobi
You can say taille de caractères for font size too
But to keep it short taille is better

James  19:35
日文應該還好 我問我老婆了（她有N1）

**Comment by scott-dt** [comment]
![Screenshot_20200904-101929](https://user-images.githubusercontent.com/62582260/92192348-64b14400-ee98-11ea-8036-b003e98840f5.png)
![Screenshot_20200904-101935](https://user-images.githubusercontent.com/62582260/92192351-65e27100-ee98-11ea-8df6-0c6f3e311c99.png)

**Comment by scott-dt** [comment]
200904 verified by scott
