### ISSUE TITLE
[FR] Wireframe for coupon mechanism

### ISSUE THREAD

**Issue by tammyyang** [MyDataTaiwan/mylog14#179]
**Concept**
If we provide wireframe for coupon mechanism

**Reason/Hypothesis**

We can help developers to better understand what to implement and help project manager to explain the feature to users. 

**More Description (if any)**

Please see flow here https://github.com/MyDataTaiwan/mylog14/issues/157

**Suggested Implementation (if any)**

N/A

**Comment by tammyyang** [comment]
Expect due: 6/9

**Comment by CS6** [comment]
![image](https://user-images.githubusercontent.com/16307922/84099743-e7169d00-aa3c-11ea-99c5-02d0a04a18a4.png)
![image](https://user-images.githubusercontent.com/16307922/84099760-ee3dab00-aa3c-11ea-8bac-9892426655fa.png)

**Comment by CS6** [comment]
[200603CouponFlow.pdf](https://github.com/MyDataTaiwan/mylog14/files/4750814/200603CouponFlow.pdf)
@tammyyang  我有整理詳細版PDF

**Comment by CS6** [comment]
[200603CouponFlow.pdf](https://github.com/MyDataTaiwan/mylog14/files/4751104/200603CouponFlow.pdf)
更新 兌換成功 Components

**Comment by tammyyang** [comment]
最後兌換成功的地方要有 `年月日時分` (目前圖上缺少時 & 分，會由 RD 端直接實作補上)
