### ISSUE TITLE
[Bug Report] Language to French can't record body temperature 

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#183]
**Description**
Language to French can't record body temperature 

**Steps to Reproduce**

1. change Language to French
2. open the app
3. Click on '+'
3. Input body temperature 
4. Click on save ( no response )

![Screenshot_20200605-110658](https://user-images.githubusercontent.com/62582260/83835038-58dfa580-a722-11ea-8605-535c9620b6f5.png)

**Environment**

* MyLog: V0.8.3
* OS:HTC EXODUS 1s,Android 8.1.0

**Comment by wcchung** [comment]
We will leave this issue on beta5 release. Change milestone to beta6 & assign Tammy

**Comment by seanwu1105** [comment]
This issue has been fixed although some text views are not translated to French in the add-record page. We should close this issue and open a new one to address these problems.

**Comment by scott-dt** [comment]
this issue fix. it can record body temperature at v0.9.0
