### ISSUE TITLE
[Bug Report]Android share link show data but a lot of data not my uploaded

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#185]
**Description**
Android share link show data but a lot of data not my uploaded. Inside the red frame my data.
image is my upload

![Android share link show](https://user-images.githubusercontent.com/62582260/83841392-589bd600-a733-11ea-861b-319997b00ded.png)

![3](https://user-images.githubusercontent.com/62582260/83841617-c8aa5c00-a733-11ea-9602-bf07f33d0d4d.png)

**Environment**

* MyLog: 0.8.3
* OS: Android 8.1.0

**Comment by shc261392** [comment]
This is a LogBoard issue (the current version of LogBoard on production site is Beta2)

**Comment by wcchung** [comment]
The issue is fixed after LogBoard release beta3
