### ISSUE TITLE
[Bug Report] Record is not saved without enter body temperature

### ISSUE THREAD

**Issue by wcchung** [MyDataTaiwan/mylog14#188]
**Description**
Record without body temperature can not be found in Daily card records.

**Steps to Reproduce**

1. Add a new record
2. Press cancel without entering body temperature
3. Add symptoms
4. Press Submit

**Expected behavior**

* Expected: Should see a record with symptoms but no temperture.
* Actual: Can not find the record without temperature in Daily Card.

**Logs**

If applicable, add logs or screenshots to help explain your problem.

**Environment**

* MyLog: 0.8.4
* OS: iOS & Android

**Comment by wcchung** [comment]
According discussion before. We can allow user to enter body temperature with "N/A" and remove the "cancel" button.

**Comment by scott-dt** [comment]
20200706 v0.11.0 ios fix verified

**Comment by scott-dt** [comment]
20200707 v0.11.2 ios & Android fix verified

**Comment by wcchung** [comment]
![image](https://user-images.githubusercontent.com/12252921/86726721-652a8b80-c05d-11ea-8c6f-1771006b18b2.png)

In v0.11.2 with cold symptoms. When user enter a record with no symptoms, the record still display 4 Data fields.

The issue is not fixed.
