### ISSUE TITLE
[Bug Report] changing language to English the regions are displayed in Chinese

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#197]
**Description**
changing language to English the regions are displayed in Chinese

![Screenshot_20200612-160914](https://user-images.githubusercontent.com/62582260/84483111-73d68a80-accb-11ea-8a3f-a479f33a326b.png)

**Environment**

* MyLog: v0.9.0
* OS: HTC EXODUS 1s,Android 8.1.0,ios 13.3.1

**Comment by scott-dt** [comment]
still show some chinese
android
![Screenshot_20200624-105317](https://user-images.githubusercontent.com/62582260/85511136-dd8b5880-b62a-11ea-808b-bb4580bb0380.png)

ios
![IMG_0679](https://user-images.githubusercontent.com/62582260/85511259-07447f80-b62b-11ea-95f1-a3062cef55a1.PNG)

**Comment by seanwu1105** [comment]
IMHO, I believe there is nothing we can do for now, unfortunately. The Chinese names in the address are provided by the inverse geocoder directly. Some road or district names might not have the English version in [Nominatim](https://wiki.openstreetmap.org/wiki/Nominatim) database. Thus, the address would be mixed with different languages.

**Comment by wcchung** [comment]
@tammyyang 根據 Sean 的回覆。此 issue 無法解決。是否要直接 close?
