### ISSUE TITLE
[Bug Report] changing language to Japanese the no Symptoms displayed in English

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#198]
**Description**
changing language to Japanese the no Symptoms displayed in English
![Screenshot_20200612-161116](https://user-images.githubusercontent.com/62582260/84483509-00814880-accc-11ea-99f3-6057c708f352.png)

**Environment**

* MyLog: v 0.9.0
* OS: Android 8.1.0,ios 13.3.1

**Comment by wcchung** [comment]
The issue is no longer exist after beta7 release
