### ISSUE TITLE
[Bug Report] changing language to French record page temperature is displayed in Chinese

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#200]
**Description**
changing language to French record page temperature is displayed in Chinese

![Screenshot_20200612-160938](https://user-images.githubusercontent.com/62582260/84484114-e431db80-accc-11ea-8e90-1d261e56c458.png)

**Environment**

* MyLog: v 0.9.0
* OS: Android 8.1.0,ios 13.3.1

**Comment by seanwu1105** [comment]
This issue has been resolved with the commit d9728cd80f5ac27601f44a7825e5342069e0c0e6.

**Comment by scott-dt** [comment]
20200706 v0.11.0 ios fix verified (english )

**Comment by scott-dt** [comment]
20200707 v0.11.2 ios & Android fix verified
