### ISSUE TITLE
[FR] The calculation of quarantine days is confusing

### ISSUE THREAD

**Issue by Pei4** [MyDataTaiwan/mylog14#201]
**Concept**
If we provide an explanation or a setting when the user first uses MyLog14.

**Reason/Hypothesis**

We can help users to understand and trust MyLog14 because we know users are sensitive and need some introduction.

**More Description (if any)**

A user indicated that she didn't know how MyLog14 knew her quarantine days (how many days left), and it makes her feel confused.

**Suggested Implementation (if any)**

If MyLog14 becomes an official app (the quarantine days might be provided by the government), maybe there should be a declaration to tell users how their quarantine days are counted and started when they first use MyLog14.
However, if it becomes a simple tool only for users to record their health conditions, then it should allow users to set up their data and starting day of quarantine.

**Comment by wcchung** [comment]
The countdown mechanism had even changed. We no longer no 14 days countdown. Instead, we set an incentive model to encourage user for using MyLog for > 7 days
https://github.com/MyDataTaiwan/mylog14/issues/212
