### ISSUE TITLE
[FR] Support heart failure symptoms

### ISSUE THREAD

**Issue by tammyyang** [MyDataTaiwan/mylog14#206]
**Concept**
If we provide heart-failure symptom forms

**Reason/Hypothesis**

We can help heart-failure patients to record their data because we know doctors need LogBoard to see life activities.

**More Description (if any)**

https://docs.google.com/spreadsheets/d/1c4vNpXjBn6WCAS0bTyVRFzIe0tv6wnxufaBZa3RX_vw/edit?usp=sharing

**Suggested Implementation (if any)**

**Comment by scott-dt** [comment]
20200706 v0.11.0 ios fix verified

**Comment by scott-dt** [comment]
20200707 v0.11.2 ios & Android fix verified
