### ISSUE TITLE
[FR] Show accumulated urine output

### ISSUE THREAD

**Issue by tammyyang** [MyDataTaiwan/mylog14#207]
**Concept**
If we user chooses to use heart-failure form, the App should show accumulated urine output in the daily card instead of the body temperature.

**Reason/Hypothesis**

We can help patients and doctors understand the most important key symptom.

**More Description (if any)**

**Suggested Implementation (if any)**

每一個 form 會有一個症狀列表
並且標註哪一個是要顯示在 daily card 上面的
根據不同的類別顯示累積、有無或者最高值

<img width="183" alt="Annotation 2020-06-18 012053" src="https://user-images.githubusercontent.com/5687908/84929214-18a8fb80-b102-11ea-8325-c46e89c018c7.png">

**Comment by wcchung** [comment]
The amount of urine display is wrong. 
I enter 2 record for urine. 
1. 15:47pm / Urine / 50ml
2. 15:48pm / Urine / 50ml

But the record showed
1. 15:47pm / Urine / **150ml**
2. 15:48pm / Urine / 50ml

**Comment by wcchung** [comment]
issue fixed in v0.11.3
