### ISSUE TITLE
[UI Update] Can set font size in Settings 

### ISSUE THREAD

**Issue by tammyyang** [MyDataTaiwan/mylog14#209]
**Update Purpose**
For some users, the current font size is too small. It will be great if we can change font size in Settings.

**UI Suggestion**

Can change small, medium, large font size in Settings.

**More Description (if any)**

Need more discussion with UI designer.

**Comment by tammyyang** [comment]
In this sprint, we only need to survey how big the impact if we change the font size

**Comment by scott-dt** [comment]
20200706 v0.11.0 ios no support

**Comment by scott-dt** [comment]
20200707 v0.11.2 ios & Android no support

**Comment by wcchung** [comment]
@seanwu1105 Can this issue can be finished in beta7 release?

**Comment by seanwu1105** [comment]
@wcchung Unfortunately, no. After the survey, this feature requires more time to be resolved since it would break the UI. Though we can only provide a partial solution by giving the users predefined font-size sets, it still needs much more time and effort to implement.

**Comment by wcchung** [comment]
@seanwu1105 What kind of support you will need for the FR?
(also cc @tammyyang )

**Comment by seanwu1105** [comment]
@wcchung IMHO, the simplest way to implement this feature is:

- Provide two or three predefined font-size configurations. (e.g. normal, large and extra-large)
- The change only applies to some parts of the app. (e.g. daily-details)

Thus, we need to first define the spec of fond-size configurations (UI design) and decide which parts of the app need to be changed before development.

**Comment by wcchung** [comment]
@seanwu1105 Thanks. I linked you and the UI volunteers in #g0v slack channel. I'll follow up with this.

**Comment by wcchung** [comment]
@seanwu1105 Can you add the estimation time for this FR?

**Comment by wcchung** [comment]
Copy Information from #g0v Slack channel

---------

Sucre  1 day ago
https://www.figma.com/file/8N647WTrETwC8mG0eHmkLm/Component?node-id=6%3A0

字型選用 @youz 推薦的 Noto Sans
(可提供多國語系)

然後
我根據Ionic 提供的H1-H6以及P整理出 Normal 的尺寸
但 Ionic 的文字尺寸都偏小
有微調幾個地方
H1的尺寸
P的尺寸
增加新的 font-style 「註解」
Letter Spacing
Line High

三個不同的尺寸，我是設定倍數進行設計
前端不一定要設定倍數(e.g. 115%, 130%)，可以直接參考我在畫面中整理出來的 Font-style
打上倍數，是方便設計這裡記錄，字型尺寸選定的邏輯

上述的內容，都有標示在文字下方
要麻煩前端特別留意

Figma 可以直接查看 Code
也可以看到我的設定，CSS的地方可以下拉
查看IOS 以及 Android 的Code

目前我已經做到一個階段
如果要更好的話
重新繪製Mylog一兩個畫面，然後模擬套用三個尺寸的樣子
標示Mylog 每個頁面，應該套用H1,H2...等

這個部分麻煩 @Sherry Chung 幫我確認一下是否需要製作，還是先由前端修改後，我再進行微調

尊重你們的工作流程

**Comment by wcchung** [comment]
According to the discussion on #g0v slack channel. The font size adjustment will be implemented with new UI in Mylog 2.0

**Comment by scott-dt** [comment]
200904 verified by scott
