### ISSUE TITLE
[FR] Create Google Apps, fill in the form and generate a unique UUID

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#211]
**Concept**
Create Google Apps, fill in the form and generate a unique UUID
Generate QR code by UUID manually

**Comment by tammyyang** [comment]
@CS6 

我們會由合作店家 (or MyLog 團隊的人協助) 來填寫 [這樣的 form](https://docs.google.com/forms/d/e/1FAIpQLSebYuxtkE1B1jGQw8lG-sOOQ5plUKRu4TgEr8D8f53d78HYyw/viewform)

填寫完以後，要自動生成 unique UUID，像是 column J of [response spreadsheet](https://docs.google.com/spreadsheets/d/1CfllOizytbMkQGglZNvafK-ecXwfMV9iQsUDshqLmjM/edit#gid=437188022)

可以想到最簡單的方式就是在 [Apps Script](https://developers.google.com/apps-script/reference/forms) 裡面去包一個 function
On Form Submit 的時候就連接 [Spreadsheet Service](https://developers.google.com/apps-script/reference/spreadsheet) 生成 UUID

如果有問題再 slack 討論囉 :)

**Comment by CS6** [comment]
![image](https://user-images.githubusercontent.com/16307922/85143852-e079f800-b27c-11ea-8ebd-5e42b7042b3f.png)

**Comment by tammyyang** [comment]
@CS6 根據之前的討論，QR code 裡面要能掃出
1. UUID
2. 店家名稱
3. 分店資訊
確切要怎麼呈現再請你直接跟 @shc261392 討論囉

**Comment by CS6** [comment]
![image](https://user-images.githubusercontent.com/16307922/85293965-a6089900-b4d0-11ea-9df7-c1752d9e2ed3.png)
https://chart.apis.google.com/chart?cht=qr&choe=UTF-8&chs=300x300&chl=%20{%20%27UUID%27:Utilities.getUuid(),%20%27%E5%BA%97%E5%AE%B6%E5%90%8D%E7%A8%B1%27:shopName,%20%27%E5%88%86%E5%BA%97%E8%B3%87%E8%A8%8A%27:shopSub,%20}

**Comment by CS6** [comment]
`{"UUID":"be105165-be37-42bb-a93c-9ce5558e74ef","shopBranch":"Coco","shopBranch":"公館分店"}`
https://chart.apis.google.com/chart?cht=qr&choe=UTF-8&chs=300x300&chl=%7B%22UUID%22:%22be105165-be37-42bb-a93c-9ce5558e74ef%22,%22shopBranch%22:%22Coco%22,%22shopBranch%22:%22%E5%85%AC%E9%A4%A8%E5%88%86%E5%BA%97%22%7D

**Comment by shc261392** [comment]
因為有兩個 `shopBranch` 在 parse 時會有 duplicate key 問題 ，我在 app 裡面先改成取 

`{"UUID":"be105165-be37-42bb-a93c-9ce5558e74ef","shopName":"Coco","shopBranch":"公館分店"}`

這樣的格式了

**Comment by shc261392** [comment]
@scott-dt QR code example
`{"UUID": "679de31a-b178-44da-abac-e0881bf14cca", "shopName": "Numbers 虛擬飲料店", "shopBranch": "線上店"}`

![qrcode](https://user-images.githubusercontent.com/24616552/85538984-f81ffa80-b647-11ea-8a29-3a0f4d02a5d3.png)

**Comment by CS6** [comment]
`
function onEdit(e) {
  var SpreadSheet = SpreadsheetApp.openById("1Hr4SGZ3hEMPakgu472Q-XEek8jcrsvMxQyQnZRGkr8E");
  Logger.log(SpreadSheet.getName());
  var values = SpreadSheet.getRange('B1:B40').getValues();
  var ALLvalues = SpreadSheet.getRange('C1:C').getValues();
  var ALLlast = ALLvalues.filter(String).length;
  var shopName=  SpreadSheet.getRange('E' + ( ALLlast)).getValues();
  var shopBranch=  SpreadSheet.getRange('F' + ( ALLlast)).getValues();
  SpreadSheet.getRange('B' + ( ALLlast)).setValue(Utilities.getUuid());
  SpreadSheet.getRange('A' + ( ALLlast)).setValue('https://chart.apis.google.com/chart?cht=qr&choe=UTF-8&chs=300x300&chl={"UUID":"'+Utilities.getUuid()+'","shopName":"'+shopName+'","shopBranch":"'+shopBranch+ '"}');
} 

`
