### ISSUE TITLE
[FR] Animation design countdown change to accumulated record 

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#213]
**Concept**
 Animation design countdown change to accumulated record

**Comment by tammyyang** [comment]
@wcchung @CS6 please help discuss with UI directly.

**Comment by tammyyang** [comment]
@wcchung 請問有結論了嗎? 是否可以請 UI/Design 開始動工了?

**Comment by scott-dt** [comment]
20200706 v0.11.0 ios only show mylog logo

**Comment by wcchung** [comment]
@CS6 Please update the survey results. How to implement? Time estimation?

**Comment by CS6** [comment]
參考連結 https://github.com/MyDataTaiwan/mylog14/issues/214#issuecomment-657344549
我再與 @shc261392  討論是否有需要分工的地方（影響到資料格式之類的）

**Comment by tammyyang** [comment]
Survey is done, move to beta8
