### ISSUE TITLE
[FR] Discuss animation

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#214]
Related issues: https://github.com/MyDataTaiwan/mylog14/issues/212 https://github.com/MyDataTaiwan/mylog14/issues/213

According to @CS6 , the current animation mechanism is not clear. For example, what should the animation area show after users collect 7-day records? Should animation stops at the latest page or start over?
 
**Concept**
Discuss animation mechanism

**Comment by tammyyang** [comment]
@scott-dt please create a spreadsheet and interview @CS6 for issues he wants to address and share with the team.

**Comment by scott-dt** [comment]
@CS6 我先將昨天會議上的問題列在sheet 上麻煩你先確認一下 我們可以再找時間討論https://docs.google.com/spreadsheets/d/1ZVllWMTMlb28kpJ0hNejSoiEHMwnU0olVjXdJn_tST8/edit?usp=sharing

**Comment by tammyyang** [comment]
@scott-dt do we have the conclusion?

**Comment by scott-dt** [comment]
@tammyyang 
目前的結論： [LOGO]>1>2>3>4>5>6> [ＢＢＴ] 停留在這 後續累積僅顯示在 coupon 頁面 所以動畫皆不會再更動只停留在最後一個動畫頁面，但最終動畫頁面需要 @wcchung 詢問醫生建議 是否維持顯示珍奶或有其他圖像顯示

**Comment by CS6** [comment]
上次UI討論沒什麼回饋，應該暫定是以愛心的方向下去做

**Comment by scott-dt** [comment]
20200706 v0.11.0 ios no support (目前顯示mylog logo圖示)

**Comment by wcchung** [comment]
> 上次UI討論沒什麼回饋，應該暫定是以愛心的方向下去做

@CS6 這個 issue 在 beta7 沒有完成，請問是否有遇到什麼瓶頸？
需要愛心的圖嗎? 是否已經決定使用哪一個愛心，或是我們就先用獎盃 (先前已經有圖了) 來進行?

**Comment by wcchung** [comment]
@CS6 Please update the estimated time to finish this FR

**Comment by CS6** [comment]
已和 @wcchung  @bafu 討論
可以參考下面圖片，目前預估動畫改版需4小時，程式改版約4小時

- ７個(紀錄累積7天，不Loop ) 一天至少一筆 

-  漸進式填滿

可選

- 做成可以重複調用的版本

![image](https://user-images.githubusercontent.com/16307922/87269107-c7243e80-c4fe-11ea-8f2c-ea6e08f641eb.png)

**Comment by tammyyang** [comment]
Survey is done, move to beta8
