### ISSUE TITLE
[Bug Report] changing language to English the delete page , address show out of range

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#220]
**Description**
changing language to English the delete page , address show out of range
ios 
![IMG_0679](https://user-images.githubusercontent.com/62582260/85510575-2098fc00-b62a-11ea-8e2d-9c6a5eb7d06d.PNG)

android
![Screenshot_20200624-105317](https://user-images.githubusercontent.com/62582260/85510779-71a8f000-b62a-11ea-804b-0a43c7b5563b.png)

**Environment**

* MyLog: v0.10.0
* OS: ios ( 13.3.1 ) , android (Android 8.1.0)

**Comment by wcchung** [comment]
Not observed in beta7 release (v0.11.3)

**Comment by wcchung** [comment]
@scott-dt 可以 confirm 一下，現在 beta7 (v0.11.3) UI 有一些改變，這個 issue 是否還在

**Comment by wcchung** [comment]
Issue not observed in beta7 (v0.11.3)
