### ISSUE TITLE
[Bug Report] when you just input symptoms no input temperature it not show the record in the daily card

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#224]
**Description**
when you just input symptoms no input temperature it not show the record in the daily card

**Steps to Reproduce**

1. Click on '+'
2. Click on 'pen icon '
3. Click on  'cancel' not input temperature 
4. it show the save message 
5. back to daily card not show the record

**Expected behavior**

* Expected: when you just input symptoms no input temperature it will show the record in the daily card
* Actual: when you just input symptoms no input temperature it not show the record in the daily card

**Environment**

* MyLog: v0.9.0
* OS: ios ,android

**Comment by wcchung** [comment]
Issue not observed in beta7 release

**Comment by wcchung** [comment]
Not observed in beta7 v0.11.3
