### ISSUE TITLE
[Bug Report] can't get coupon

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#226]
**Description**
can't get coupon

**Steps to Reproduce**

1. Record for 14 days
2.  click " bubble icon "
3. show coupon page 

**Expected behavior**

* Expected: can go to QR code scanner page , can get the coupon
* Actual: show out of stock & No points ,can't get the coupon

![IMG_0693](https://user-images.githubusercontent.com/62582260/85964606-cfec1f00-b9ec-11ea-8469-c56d83df6759.PNG)

**Environment**

* MyLog: v 0.10.0
* OS: ios 13.5.1 ( iphone 7 plus )

**Comment by scott-dt** [comment]
can get coupon on Android

**Comment by scott-dt** [comment]
this issue in [ ios 13.3.1 ] it show correct information but can't open QR code scanner page.

**Comment by scott-dt** [comment]
20200706 v0.11.0 ios  還是一樣一直轉圈圈無法進入QR code 頁面

**Comment by scott-dt** [comment]
20200707 v0.11.2 ios & Android 目前可兌換金額 一直轉圈圈無法進入QR code 頁面

**Comment by scott-dt** [comment]
20200709 v0.11.3 ios & Android 目前可兌換金額 一直轉圈圈無法進入QR code 頁面

**Comment by wcchung** [comment]
The issue will blocking open beta test campaign in the end of July. Adjust priority to critical

**Comment by tammyyang** [comment]
測試 API https://mylog-backend.bubbleapps.io/version-test/api/1.1/wf/poolbalance 可正常獲得 pool balance

**Comment by scott-dt** [comment]
目前剩餘金額可顯示金額，但無法進入QR code scan (一直轉圈圈 )
![File](https://user-images.githubusercontent.com/62582260/87379378-ad4c2f80-c5c2-11ea-97d1-e1f93358a360.jpg)

**Comment by scott-dt** [comment]
目前可兌換金額空白 且剩餘兌換名額顯示暫無名額
![Screenshot_20200715-093832](https://user-images.githubusercontent.com/62582260/87494004-953ae580-c680-11ea-9aac-208184c8d720.png)
Environment
MyLog: v 0.11.4
OS: Android 8.1.0

**Comment by wcchung** [comment]
According to the discussion on demo on 2020/7/15, the issue will be postponed to beta8

cc @tammyyang

**Comment by scott-dt** [comment]
7/23 v0.11.6 Android fix verified

**Comment by scott-dt** [comment]
7/23 v0.11.6 ios can't open the QRcode scanner

**Comment by wcchung** [comment]
Discussed & confirmed with @tammyyang on 2020/7/27, postpone to beta9

```
sherry  16:19
@Tammy 根據早上的 Marvin sync-up，MyLog beta8 的兩個 issue 都會延到 beta9 才完成，這樣是否把beta8 的 issue 移到 beta9 並 close beta8
https://github.com/MyDataTaiwan/mylog14/milestone/11
:ok_hand::skin-tone-2:
1
:+1::skin-tone-2:
1
```
