### ISSUE TITLE
[FR] 使用者兌換介紹頁面

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#228]
**Concept**
使用者兌換介紹頁面

**Reason/Hypothesis**
可以讓使用者清楚知道有那些兌換商家目前可以進行兌換

**More Description (if any)**
目前沒有任何地方顯示可進行兌換的商家有哪些

**Suggested Implementation (if any)**
目前 以 app 內放入 網頁連結  如下圖紅框位置放置一連結位置
![Screenshot_20200713-161805](https://user-images.githubusercontent.com/62582260/86328538-8a8f5200-bc77-11ea-9bfe-c1c16bbd5afb.png)

此連結點選後會進入網頁 ( bubble 製作的兌換商家清單 )

**Comment by wcchung** [comment]
@scott-dt According to the comment in [Coupon 機制流程 SOP](https://docs.google.com/document/d/1slwZmMTv6KCbc4f5QyMbVdGvClXyr3n4GBkHIGDLsAo/edit?usp=sharing). Please move this issue to Milestone Beta8

**Comment by wcchung** [comment]
@CS6 商家介紹頁面已提供  https://mydata.org.tw/version-test/mylogcoupon

**Comment by scott-dt** [comment]
200804 v0.12.0 沒有任何地方可以連結進商家頁面
