### ISSUE TITLE
[Bug Report] Add the picture and close the application immediately. Picture is not saved (only ios )

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#229]
**Description**
Add the picture and close the application immediately. Picture is not saved. 

**Steps to Reproduce**

1. Click on '+'
2. Click on ' pen icon '
3. make sure the record show on the daily card
4. Click on '+'
5. Click on ' camera icon '
6. make sure the picture show on the daily card
7. close the app ( Background close up )
8. open the app 
9.  the picture disappear on the daily card

**Expected behavior**

* Expected: Add the picture and close the application immediately. Picture is will saved and reopen the app it show on daily card
* Actual: Add the picture and close the application immediately. Picture is not saved

**Environment**

* MyLog: v0.10.0
* OS: ios 13.5.1

**Comment by wcchung** [comment]
Issue not observed in beta7 (v0.11.3)
