### ISSUE TITLE
[FR] 健康聲明特別版

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#237]
**Concept**
讓 MyLog 有一個健康聲明 form 、然後可以上傳到 LogBoard 顯示
1. 基於 MyLog 0.9 版 新增健康聲明 form
2. 修改前端讓它 只顯示當日資料 (要能清楚看到體溫、時間、地點)
3. 請 James 把這個客製化的 LogBoard 掛在新的 AWS instance
4. 修改 MyLog 的 LogBoard 位址
5. 出 Android & iOS 的 Open Beta

**Reason/Hypothesis**
做防疫資料收集 

**Suggested Implementation (if any)**
健康聲明 form 內容 : 
體溫 (數字):
請問你過去十四天是否
* 有出國 (toggle)
 note 填入國家
* 有發燒 (toggle)
 note 填入發燒情形
* 接觸過正在檢疫或隔離的人士 (toggle)
 note 填入為何接觸
* 接觸過旅遊至高風險的人士 (toggle)
然後強制中文 (關掉 i18n) (edited)

**Comment by tammyyang** [comment]
Beta9 task:

1. Create a wiki page to teach community members how to add new forms and send PR
2. Add 健康聲明 form to MyLog

**Comment by wcchung** [comment]
新增健康聲明症狀包可供選擇。且當使用者分享健康聲明內容時，其餘症狀包裡的 health 紀錄不會被一起分享出去，僅過去最多 14 天的健康聲明紀錄可被輸出

**Comment by scott-dt** [comment]
0.13.1可記錄健康聲明
