### ISSUE TITLE
[Bug Report] Initial installation input the email, at setting page no show the email

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#239]
**Description**
Initial installation input the email, at setting page no show the email

**Steps to Reproduce**

1. install the app
2. input the email , Click on " confirm "
3. go to setting page 
4. email show " not set "

**Environment**

* MyLog: v0.11.2
* OS:  Android 10, iOS

**Comment by wcchung** [comment]
Can not distinguish the email is `saved but not shown in setting page` or the email is `not saved`

**Comment by tammyyang** [comment]
The objective of beta7 is HF record, move other issues to beta8

**Comment by scott-dt** [comment]
0.11.4 fix verified on ios
