### ISSUE TITLE
[Bug Report] Update old version to v0.11.2 ,can't record directly 

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#240]
**Description**
Update old version to v0.11.2 ,can't record directly ,need to setting page switch select record mode . 

**Steps to Reproduce**

1. update version to 0.11.2 
2. can't record directly  
3. go to setting page
4. switch select record mode to the other one
5. can record 

**Expected behavior**

* Expected: Update old version to v0.11.2 ,can record directly
* Actual: Update old version to v0.11.2 ,can't record directly

**Logs**

If applicable, add logs or screenshots to help explain your problem.

**Environment**

* MyLog: v0.11.2
* OS:  Android 10, iOS

**Comment by wcchung** [comment]
issue fixed in v0.11.3
