### ISSUE TITLE
[Bug Report] can't upload the record to logboard

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#241]
**Description**
can't upload the record to logboard

**Expected behavior**

* Expected: can upload the record to logboard
* Actual: can't upload the record to logboard

**Environment**

* MyLog: v0.11.2
* OS: Android , iOS

**Comment by tammyyang** [comment]
This is expected, beta7 does not support HF data format upload to LogBoard, move to beta8

**Comment by scott-dt** [comment]
7/23 beta8 v0.11.6 尚不能上傳 ，週五 release 之後現在產生的連結會指向新的 LogBoard

**Comment by scott-dt** [comment]
7/27 beta8 v0.11.6 可上傳至 logboard beta5

**Comment by wcchung** [comment]
Discussed & confirmed with @tammyyang on 2020/7/27, postpone to beta9

```
sherry  16:19
@Tammy 根據早上的 Marvin sync-up，MyLog beta8 的兩個 issue 都會延到 beta9 才完成，這樣是否把beta8 的 issue 移到 beta9 並 close beta8
https://github.com/MyDataTaiwan/mylog14/milestone/11
:ok_hand::skin-tone-2:
1
:+1::skin-tone-2:
1
```

**Comment by scott-dt** [comment]
7/27 包含圖片上傳失敗問題
 fix by james 
 fix verified by scott

**Comment by scott-dt** [comment]
200804 v0.12.0 上傳不穩定 ( ios & Android ) 早上測試兩次上傳都有成功 ( 第一次與第二次無新增資料直接上傳 ) 12點的時候怎麼試都顯示上傳失敗請稍後再試
p.s: 測試過將版本退回 v 0.11.6 也顯示上傳失敗請稍後再試 
![Screenshot_20200804-115726](https://user-images.githubusercontent.com/62582260/89251582-f5062a00-d649-11ea-9cb5-808218699168.png)

**Comment by scott-dt** [comment]
v0.12.0 上傳失敗  我測試後發現需要
1. 進到設定
2. 開啟開發人員選項
3. 將上傳測試設定 調整為 " Dev " 
調整過後上傳就很穩定 上傳5次都沒有再失敗過

**Comment by wcchung** [comment]
Copy from Slack channel. Confirmed this is not a issue in beta9

-------

Scott Yan  14:28
@James 上傳失敗的部分我測試好幾次 發現進到開發人員選項將上傳測試設定點選為" Dev " 之後就很穩定的連續上傳5次都有成功 如果沒有進去設定就要看機運有時候成功有時候失敗

James  14:28
@Scott Yan 那麻煩每次都設一下

1 reply
10 days agoView thread

Scott Yan  14:29
replied to a thread:
@Scott Yan 那麻煩每次都設一下
但使用者不會知道這個設定所以他還是一個issues 需要修正喔~~感謝 (edited) 

James  14:29
如果有設就 一定不會上傳失敗 ，那這並不是 release blocker ，因為這樣表示是跟開發人員選項設定沒存好有關係
14:29
現在會上傳失敗的原因是因為 production site 目前不提供上傳
