### ISSUE TITLE
[Bug Report] 紀錄症狀為勾選 ， 日期卡上會顯示所有症狀

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#242]
**Description**
紀錄症狀為勾選 ， 日期卡上會顯示所有症狀 。 ( 雖然後方有顯示"是","否"，但與先前 ux 設計不同 )
且更換為心衰竭症狀包時 沒有輸入資料的症狀即不顯示 ( 狀態與一般感冒症狀包顯示方式不同 )

**Expected behavior**

* Expected: 沒有勾選症狀則不顯示症狀在日期卡上
* Actual: 沒有勾選的症狀會顯示在日期卡上 ( 雖然後方有顯示"是","否"，但與先前 ux 設計不同 ) 

**Logs**
![86727941-7cb64400-c05e-11ea-9b3e-8f28a14d0658](https://user-images.githubusercontent.com/62582260/86729966-9d7f9900-c060-11ea-8cdd-5dd3cb58344c.png)

![File](https://user-images.githubusercontent.com/62582260/86730833-81c8c280-c061-11ea-9dfd-49050ab58f3d.jpg)

**Environment**

* MyLog: v0.11.2
* OS:Android , iOS

**Comment by wcchung** [comment]
fixed in v0.11.3
