### ISSUE TITLE
[Bug Report] Language is set to English , input blood pressure can't show keyin numbers

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#243]
**Description**
Language is set to English , input blood pressure can't show keyin numbers

**Logs**
![Screenshot_20200707-095258](https://user-images.githubusercontent.com/62582260/86731517-32cf5d00-c062-11ea-9e7c-a44b40b82964.png)

**Environment**

* MyLog: v0.11.2
* OS: Android , iOS

**Comment by wcchung** [comment]
fixed in v0.11.3
