### ISSUE TITLE
[FR] 在完全沒有輸入任何症狀體溫(全部留白)按下 " 送出 " 時，可跳出警告視窗未填寫任何資料

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#244]
**Concept**
在完全沒有輸入任何症狀體溫(全部留白)按下 " 送出 " 時，可跳出警告視窗未填寫任何資料

**Reason/Hypothesis**
提醒使用者未輸入任何資料

**Suggested Implementation (if any)**

建議至少一項紀錄有數值 否則跳出警告視窗告知使用者尚未填寫任何資料

**Comment by scott-dt** [comment]
目前 0.11.4 ios & Android 
1. 進入紀錄頁面全部留白
2. 按下 " 送出 "
3. 顯示記錄成功
4. 回到日期卡 
    a. 當日先前已有紀錄資料 ，不會有任何剛剛空白的紀錄
    b. 當日第一筆紀錄資料 ， 會新開一個日期卡但日期卡內不會有資料

**Comment by wcchung** [comment]
當 user 送出空白資料時，可能有兩種情況
1. user 單純只想記錄 location，而不輸入任何資料
2. user 誤按了，沒有要輸入任何資料

如果是 case 1，則當 user 沒有輸入任何資料時，不需跳出警告視窗。
如果是 case 2，則建議跳出警告視窗

**Comment by scott-dt** [comment]
目前無紀錄仍可顯示成功紀錄 但日期卡上不會有資料顯示

**Comment by wcchung** [comment]
Copy from Slack, move this issue to Backlog

```
tammy  02:30
replied to a thread:
@Tammy (cc @James)…
@sherry 抱歉今天比較忙回晚了
針對尚未修的 issue list，我打開看過了，基本上都是 priority-medium or 'priority-low ，所以屬於 better-to-have，尚未完成是預期中的，那就請你移到 backlog or next milestone，剩下的可以關掉了 :tada:
```

**Comment by scott-dt** [comment]
![Screenshot_20200904-162340](https://user-images.githubusercontent.com/62582260/92217996-0782b600-eecb-11ea-9e7e-3d7dc9685a62.png)
200904 verified by scott
