### ISSUE TITLE
[UI Update] No need to set the high /low boundary in HF data

### ISSUE THREAD

**Issue by wcchung** [MyDataTaiwan/mylog14#263]
**Update Purpose**
No need to set high / low boundary in HF data

![image](https://user-images.githubusercontent.com/12252921/89210561-e7718580-d5f2-11ea-85fb-85d6eaeb3281.png)

**UI Suggestion**

* Remove hight/ low boundary

**More Description (if any)**

Put more description here to help developers understand

**Comment by scott-dt** [comment]
目前測試確認沒有設限 ( 測試2000 尿量10000 )
