### ISSUE TITLE
[FR] Show SBP instead of urine-volume in the center of each record (for HF data)

### ISSUE THREAD

**Issue by wcchung** [MyDataTaiwan/mylog14#264]
**Concept**
If we will show 1 data for each record, it should be the most important data. Take HF for example, that will be SBP / DBP

![image](https://user-images.githubusercontent.com/12252921/89211376-4daad800-d5f4-11ea-9c06-fb9491d10422.png)

**Reason/Hypothesis**

We can help user to see SBP / DBP in the daily card record summary because we know they are the most important data.

**More Description (if any)**

**Suggested Implementation (if any)**

Showing SBP / DBP in the summary of each record

**Comment by wcchung** [comment]
@shc261392 跟台大藥學系教授確認後，此欄位改為 Systolic blood pressure 收縮壓即可

**Comment by scott-dt** [comment]
確認已改為當日最高收縮壓

**Comment by wcchung** [comment]
將每筆 record 的 summary 改為收縮壓的同時，左上方 daily card 的 summary 也改為 「最高收縮壓」。
一開始沒有預期這兩個值會一起連動修改。會先開一個 issue 紀錄這件事情，並 confirm 使用者的需求。
 (cc @tammyyang )

![image](https://user-images.githubusercontent.com/12252921/90851074-34e94300-e3a6-11ea-8081-d96685f84782.png)

**Comment by wcchung** [comment]
see https://github.com/MyDataTaiwan/mylog14/issues/276
