### ISSUE TITLE
[UI Update] Increase font size

### ISSUE THREAD

**Issue by wcchung** [MyDataTaiwan/mylog14#265]
**Update Purpose**
For most elder users, especially for the patient with HF. The current font size is too small. It will be great if we can increase the font size.

**UI Suggestion**

Increase font size

**More Description (if any)**

ref: #209 #178

**Comment by wcchung** [comment]
MyLog Font Size 測試在分頁二 https://www.figma.com/file/Q1U8c47FR6T5qIangQM9dg/MyLogFont?node-id=6%3A0

**Comment by wcchung** [comment]
標題: 18PT; 輸入之內容: 26 PT (or > 24 PT)
----------
![image](https://user-images.githubusercontent.com/12252921/90367483-7ecae400-e09b-11ea-8c34-ceacafe1d23e.jpeg)

內容: 18PT; 最上面的標題: 22 PT
----------
![image](https://user-images.githubusercontent.com/12252921/90367507-82f70180-e09b-11ea-822e-1587a1ea51f4.jpeg)

內容: 18PT; 最上面的標題: 22 PT
----------
![image](https://user-images.githubusercontent.com/12252921/90367531-87231f00-e09b-11ea-9b03-5799029a92d8.jpeg)

**Comment by scott-dt** [comment]
字體有加大了 但版面都跑掉了 跑版問題詳見 issues #271
