### ISSUE TITLE
無法安裝

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#27]
1. 下載 apk (https://github.com/MyDataTaiwan/mylog14/releases/tag/V0.4.1-alpha.1) 
2. 電腦與手機連線 ( usb 傳檔模式 )
3. 將 MyLog14_V0_4_1-alpha.1.apk 放入 Download 資料夾
4. 手機點選進入 Download 資料夾點選 " MyLog14_V0_4_1-alpha.1.apk " ，執行安裝
5. 顯示  " 未安裝應用程式 "  ， 點選 " 完成 "
6. 跳出安裝

![Screenshot_20200410-180938](https://user-images.githubusercontent.com/62582260/78983862-9deabf80-7b57-11ea-884e-1070166389bb.png)

**Comment by shc261392** [comment]
v0.4.1 已修正此問題
