### ISSUE TITLE
[Bug Report] iphone跑版問題

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#271]
**Description**
上方titel 每一個頁面都跑版
按鍵的部分重疊

![IMG_0811](https://user-images.githubusercontent.com/62582260/90762977-80eda680-e318-11ea-8f42-ead2391d2daa.PNG)
![IMG_0816](https://user-images.githubusercontent.com/62582260/90762980-81863d00-e318-11ea-9554-0c12a2a11ef0.PNG)
![IMG_0813](https://user-images.githubusercontent.com/62582260/90762984-82b76a00-e318-11ea-8fee-4bbffed36bd1.PNG)
![IMG_0812](https://user-images.githubusercontent.com/62582260/90762989-83e89700-e318-11ea-9106-c6fcc46335fb.PNG)
![IMG_0814](https://user-images.githubusercontent.com/62582260/90762994-8519c400-e318-11ea-8ce8-9849cde82e9e.PNG)

**Environment**

* MyLog: 0.13.1
* OS:  iOS 13 /iphone 7 plus

**Comment by CS6** [comment]
![image](https://user-images.githubusercontent.com/16307922/91364088-968b3080-e830-11ea-8f2b-a6c5ccf0ff35.png)
![image](https://user-images.githubusercontent.com/16307922/91364099-9a1eb780-e830-11ea-9d56-cc6a2725ad1f.png)
![image](https://user-images.githubusercontent.com/16307922/91364127-a60a7980-e830-11ea-8015-10a5ae0ac7e6.png)

**Comment by scott-dt** [comment]
英日法 兌換20點按鈕皆跑版如下圖
步驟
1. 點選 "愛心" icon
2. 兌換頁面 (當帳號為可兌換時)
![IMG_0833](https://user-images.githubusercontent.com/62582260/91921572-66470480-ecfe-11ea-858a-1acae7d9bb1d.PNG)

**Comment by scott-dt** [comment]
相片刪除確認對話框確認按鍵 英日法皆跑版
步驟
1. 進入相片頁面
2. 點選相片
3. 點選由上角"刪除" 按鍵
4. 跳出確認刪除頁面
![IMG_0834](https://user-images.githubusercontent.com/62582260/91922121-b83c5a00-ecff-11ea-83fa-4a480f589b4a.PNG)

**Comment by scott-dt** [comment]
![File](https://user-images.githubusercontent.com/62582260/92192507-b528a180-ee98-11ea-86ba-31587c6789ba.jpg)

**Comment by scott-dt** [comment]
200904 verified by scott
