### ISSUE TITLE
[Bug Report] 舊版0.12.3 升至 0.13.1 email 沒有重新驗證，先前版本的資料無法顯示

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#273]
**Description**
舊版的直升後不重新驗證，回到日期卡是空的沒有顯示任何先前的資料

**Steps to Reproduce**
1. 舊版0.12.3 直接更新 0.13.1 
2. 進入 app 
3. 顯示 error "cannot resd property 'dataClass' of undefined"

**Expected behavior**

* Expected: 回到日期卡顯示先前紀錄的資料
* Actual: 回到日期卡是空的沒有顯示任何先前紀錄的資料

![Screenshot_20200821-092918](https://user-images.githubusercontent.com/62582260/90847454-221e4080-e39d-11ea-8164-1ed39271f482.png)
![Screenshot_20200821-094645](https://user-images.githubusercontent.com/62582260/90847459-23e80400-e39d-11ea-8890-bdfecd47a78a.png)
![Screenshot_20200821-094707](https://user-images.githubusercontent.com/62582260/90847464-25193100-e39d-11ea-90c7-0ccddc8333fc.png)

**Environment**

* MyLog: 0.13.1、0.12.3
* OS:  iOS 13/iphone7 plus、Android8.1.0/HTC 1s

**Comment by wcchung** [comment]
[Copy from Slack]

```
tammy  02:30
replied to a thread:
@Tammy (cc @James)…
@sherry 抱歉今天比較忙回晚了
針對尚未修的 issue list，我打開看過了，基本上都是 priority-medium or 'priority-low ，所以屬於 better-to-have，尚未完成是預期中的，那就請你移到 backlog or next milestone，剩下的可以關掉了 :tada:
關於其他的兩個問題
A. 字體放大的部分可能是因為手機螢幕尺寸不同，我傾向同之前規劃的用 beta9 做封測，然後加一個 RC1 milestone 請 Dayuan 協助調整 (如果 James 也覺得適合的話)
B. 過去的資料會被刪除的部分，我想先知道為什麼 (資料存在手機上，為何會因為驗證被刪除?)，如果有機會在 4-8 小時內修正 (不含測試)，會請 James 加入 RC1 release 當中，如果不是短期可克服，則在上架時加入 Warning
```

**Comment by wcchung** [comment]
[Copy From Slack] 

James  12:22
@Tammy @sherry B 的部分我的理解是這樣的，如果測試上遇到的狀況不是這樣再請跟我說一下
1. 如果 user 的 email 沒有經過驗證，就無法成功登入（可以進入主畫面，但不能使用 coupon 兌換流程）
2. （理論上此時應該要跳出畫面讓 user 收驗證信驗證現有的 email ，但目前沒有）
3. 因為 user 無法使用 coupon 兌換，唯一能夠使用的方式就是點選設定頁面的重設帳號，清除所有資料並且重設 email （重設 email 必須清除資料的設定是 為了在 Beta 9 版本防止 user 透過不斷重設 email 無限兌換 coupon ，在已經有 email 驗證的版本實作上可以改成讓 user 重收驗證信而不需要清除資料 ，只是目前此塊功能未改）

**Comment by shc261392** [comment]
Fixed on 4ad00580422a3d4ea5a3edf11df8c4aa8d0440a2

**Comment by scott-dt** [comment]
200904 verified by scott
