### ISSUE TITLE
[Feature Report] 初次 使用app 輸入email 跳出提示訊息可調整

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#274]
**Concept**
驗證信已寄出 -> 請至信箱收信並驗證後再次點擊 "確認"進入
(使用者會不清楚驗證後如何再次進入app)
**Reason/Hypothesis**
目前僅顯示驗證信已寄送到你的電子郵件信箱 ，信箱驗證完後需要回到 "app" 再按一次 "確認" 才能進入
(使用者會不清楚驗證後如何再次進入app)

**More Description (if any)**
建議修改成 "驗證信已寄出，請至信箱收信並驗證後再次點擊 "確認" 進入 " 將後續步驟流程也寫入
![Image from iOS (1)](https://user-images.githubusercontent.com/62582260/90848346-395e2d80-e39f-11ea-9214-2b1b120360b6.png)

**Comment by CS6** [comment]
@wcchung 
由於 “emailVerification”: “驗證信已寄出到你的電子郵件信箱。 已改成==> 驗證信已寄出，請至信箱收信並驗證後再次點擊“確認“進入”
可以請你幫忙向社群要另外三種語言的翻譯嗎？
“emailVerification”: “登録したメールアドレスに認証メールを送りました。”
“emailVerification”: “Un e-mail de vérification a été envoyé à votre adresse e-mail.”
“emailVerification”: “A verification email has been sent to your email address.”

**Comment by wcchung** [comment]
英文: A verification email has been sent to your email address. Please check your inbox and press "Confirm" to complete the verification.
中文: 驗證信已寄出，請至信箱收信並驗證後再次點擊“確認“進入
日文: 承認メールをあなた宛に送信しました。メールの「決定」ボタンを押して承認をお願いします。
法文: Un email de vérification a été envoyé à votre adresse.  Merci de vérifier votre boite de réception et de cliquer sur "confirmer" pour terminer la vérification.

@CS6

**Comment by scott-dt** [comment]
![Screenshot_20200904-161228](https://user-images.githubusercontent.com/62582260/92216947-955da180-eec9-11ea-98ee-e24e993b036b.png)
200904 verified by scott
