### ISSUE TITLE
[Bug Report]  Android 跑版問題

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#275]
**Description**
按鈕重疊 切到邊框

![Screenshot_20200821-100656](https://user-images.githubusercontent.com/62582260/90848722-27c95580-e3a0-11ea-8aba-cd7be2216d5e.png)
![Screenshot_20200821-104436](https://user-images.githubusercontent.com/62582260/90848723-2861ec00-e3a0-11ea-9b19-a9453602d80e.png)
![Screenshot_20200821-104451](https://user-images.githubusercontent.com/62582260/90848727-29931900-e3a0-11ea-9891-5bdb2bf6daf1.png)

**Environment**

* MyLog : 0.13.1
* OS: Android 8.1.0/HTC 1s

**Comment by CS6** [comment]
![image](https://user-images.githubusercontent.com/16307922/91207679-b8ef5200-e73b-11ea-9c28-bcefe8b43c5c.png)

![image](https://user-images.githubusercontent.com/16307922/91210302-97906500-e73f-11ea-80f2-cee0c07cdbe6.png)

![image](https://user-images.githubusercontent.com/16307922/91213274-ec35df00-e743-11ea-90eb-ad7ecf251745.png)


![image](https://user-images.githubusercontent.com/16307922/91213329-01ab0900-e744-11ea-864c-f793cb85252b.png)

**Comment by scott-dt** [comment]
200904 verified by scott
