### ISSUE TITLE
[Bug Report] 上傳資料至 prod sit  點擊 link 後無法顯示資料

### ISSUE THREAD

**Issue by scott-dt** [MyDataTaiwan/mylog14#277]
**Description**
上傳資料至 prod sit  點擊 link 後無法顯示資料

**Steps to Reproduce**

1. app 設定上傳測試設定選擇 " Production "
2. 上傳資料 ， 取得 link 於電腦上chrome 瀏覽器開啟
3. 會一直呈現資料讀取的轉圈圈畫面

**Logs**
資料連結 : https://logboard.numbersprotocol.io/caf86889-e856-45ae-b7ad-1f08c7c583f6
![image](https://user-images.githubusercontent.com/62582260/90871439-af798900-e3cd-11ea-863c-7864026bbb93.png)

**Environment**

* MyLog: v0.13.1
* OS:  iOS 13/iphone7 plus & chrome  / 84.0.4147.125

**Comment by shc261392** [comment]
這是因為目前 https://logboard.numbersprtocol.io (logboard-frontend prodution site) 串接到舊的 https://logboard-dev.numbersprotocol.io API ，應該檢查 logboard-frontend 的 API host 和 deploy 參數設定

**Comment by shc261392** [comment]
Fixed in https://github.com/MyDataTaiwan/logboard-frontend/commit/53b4220b96595eb5b47a5bcff6d55fbba7b56c66

**Comment by scott-dt** [comment]
200826 測試正常顯示
![image](https://user-images.githubusercontent.com/62582260/91372678-d6f5a900-e846-11ea-9512-7f25a7faf9c0.png)
