### ISSUE TITLE
[Bug Report] Can not upload data to LogBoard prod (V0.11.6, v0.12.2 & v0.12.3)

### ISSUE THREAD

**Issue by wcchung** [MyDataTaiwan/mylog14#278]
**Description**
User can not upload data to LogBoard (prod site) in v0.11.6 (beta8), v0.12.2 (beta9) & v0.12.3 version

**Steps to Reproduce**

1. Go to Upload page in MyLog APP
2. Select upload data

**Expected behavior**

* Expected: Can generate a link & upload data to LogBoard.
* Actual: Show error while upload to LogBoard.

**Logs**
v0.12.2 & v0.12.3
![image](https://user-images.githubusercontent.com/12252921/90951259-bf57a280-e48b-11ea-87f4-c4deaa517b35.png)

v0.11.6
![image](https://user-images.githubusercontent.com/12252921/90951266-d3030900-e48b-11ea-8896-2858bd95288a.png)
If applicable, add logs or screenshots to help explain your problem.

**Environment**

* MyLog: v0.12.2, v0.12.3, v0.11.6
* OS: iPhone 13.5.1

**Comment by shc261392** [comment]
The old host `mylog14.numbersprotocol.io` doesn't have a valid SSL certificate, so one iOS and Android the HTTP request is blocked for security reason.

After retrieving updated SSL certificate on production site (for both `mylog14.numbersprotocol.io` and `api.logboard.numbersprotocol.io` ), this issue should be fixed.

**Comment by scott-dt** [comment]
200827 測試可正常上傳 prod sit
