### ISSUE TITLE
[FR] User can re-verify their email address 

### ISSUE THREAD

**Issue by wcchung** [MyDataTaiwan/mylog14#282]
**Concept**
If we provide user to re-verify their email, user can keep their previous data while update new version.

**Reason/Hypothesis**

**More Description (if any)**

Put more description here to support the concept

**Suggested Implementation (if any)**

Put some suggested implementation here if you already have some ideas in mind

**Comment by wcchung** [comment]
[Copy from Slack]

--------------------------
tammy  02:30 2020/8/21
replied to a thread:
@Tammy (cc @James)…
@sherry 抱歉今天比較忙回晚了
針對尚未修的 issue list，我打開看過了，基本上都是 priority-medium or 'priority-low ，所以屬於 better-to-have，尚未完成是預期中的，那就請你移到 backlog or next milestone，剩下的可以關掉了 :tada:
關於其他的兩個問題
A. 字體放大的部分可能是因為手機螢幕尺寸不同，我傾向同之前規劃的用 beta9 做封測，然後加一個 RC1 milestone 請 Dayuan 協助調整 (如果 James 也覺得適合的話)
B. 過去的資料會被刪除的部分，我想先知道為什麼 (資料存在手機上，為何會因為驗證被刪除?)，如果有機會在 4-8 小時內修正 (不含測試)，會請 James 加入 RC1 release 當中，如果不是短期可克服，則在上架時加入 Warning

----------------------------
James 12:22 2020/8/24
@tammy @sherry B 的部分我的理解是這樣的，如果測試上遇到的狀況不是這樣再請跟我說一下

如果 user 的 email 沒有經過驗證，就無法成功登入（可以進入主畫面，但不能使用 coupon 兌換流程）
（理論上此時應該要跳出畫面讓 user 收驗證信驗證現有的 email ，但目前沒有）
因為 user 無法使用 coupon 兌換，唯一能夠使用的方式就是點選設定頁面的重設帳號，清除所有資料並且重設 email （重設 email 必須清除資料的設定是 為了在 Beta 9 版本防止 user 透過不斷重設 email 無限兌換 coupon ，在已經有 email 驗證的版本實作上可以改成讓 user 重收驗證信而不需要清除資料 ，只是目前此塊功能未改）

**Comment by shc261392** [comment]
Fixed on a63779f6989a918a704d41da4ff3ddf4015532af

**Comment by scott-dt** [comment]
200904 verified by scott  更新點選兌換頁面會顯示重新驗證信箱頁面 不會清除資料
