### ISSUE TITLE
[FR] 支援鼻咽癌術後記錄 form 

### ISSUE THREAD

**Issue by tammyyang** [MyDataTaiwan/mylog14#290]
(WIP)
**Concept**
If we provide [Feature]

**Reason/Hypothesis**

We can help [who] to [Benefit] or solve [Problem] because we know [who] are [Fact about our target].

**More Description (if any)**

Put more description here to support the concept

**Suggested Implementation (if any)**

Put some suggested implementation here if you already have some ideas in mind

**Comment by shc261392** [comment]
Suggested implementation:

1. Add a new JSON file in https://github.com/MyDataTaiwan/mylog14/tree/develop/src/assets/data-templates . The filename and JSON schema should follow the current pattern.

2. Add the corresponding translations in https://github.com/MyDataTaiwan/mylog14/blob/develop/src/assets/i18n/en.json

**Comment by bafu** [comment]
I will finish this task before the end of 9/22 (Tue.)

**Comment by bafu** [comment]
鼻咽癌術後需要紀錄的指標

1. 發生暈眩 (dizziness) 時當下的程度與時間
    - 程度分類
        - 低：輕微且立即恢復
        - 中：感到不舒服且持續超過一分鐘
        - 高：無法行走
1. 發生心悸 (palpitation) 時當下的程度與時間
    - 程度分類：同暈眩
1. 定期紀錄血壓

**Comment by scott-dt** [comment]
10/15 ios 版以測試完成 pass , Android 版還在等待尚未於play store 尚可下載

**Comment by scott-dt** [comment]
10/28 Android 版 ， 已經可以於 GPlay 上下載並進行安裝 ，完成測試 pass
