### ISSUE TITLE
[Todo] Adjust the FAB button style

### ISSUE THREAD

**Issue by shc261392** [MyDataTaiwan/mylog14#40]
# Issue description

Chloe:
a. icon 改成白底
b. 稍微推高一點，不要跟 bar 主要的按鈕重疊
c. 改成相機跟筆的 icon

**Comment by shc261392** [comment]
Done

**Comment by shc261392** [comment]
Feature request from UI: FAB button 位置可以再調高一點，大約和 + 鈕呈 45 度角高度

**Comment by CS6** [comment]
基於 issues #65    我覺得可以關閉這個issue @shc261392 
 https://github.com/MyDataTaiwan/mylog14/issues/65
