### ISSUE TITLE
Some keywords are refering to Taiwan

### ISSUE THREAD

**Issue by dixonsiu** [MyDataTaiwan/mylog14#79]
For global support, you might need to change "Taiwan" to "Your country" or "Home".

https://github.com/MyDataTaiwan/mylog14/blob/master/src/assets/i18n/en.json#L26

Also Hong Kong people select English but living in Japan would feel strange to see "US" in the screen.

**Comment by bafu** [comment]
Thanks Dixon! It's a valid suggestion and we have globalized the app introduction.
